name: Publish to Artifactory

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Doxygen version `rel-1.9.2`'     
        required: true
        default: 'rel-x.y.z'

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_CLI_SECRET }}
      - name: Download
        run: ./download-doxygen.sh "$VERSION"
      - name: Upload
        run: jfrog rt u ${{ github.event.inputs.version }}/  generic-release-mirror/doxygen/
